// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIDLhU3h8khQFQ0dtJXoR48dcKNK6y6SI',
    appId: '1:138938830840:web:2ca14f996c8e3ffab8900d',
    messagingSenderId: '138938830840',
    projectId: 'todo-db9a3',
    authDomain: 'todo-db9a3.firebaseapp.com',
    storageBucket: 'todo-db9a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-pbD_XVNyBzALNfxt3oc30kEVn24CCE',
    appId: '1:138938830840:android:5ec2614a34f44768b8900d',
    messagingSenderId: '138938830840',
    projectId: 'todo-db9a3',
    storageBucket: 'todo-db9a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDntiT_eQb285W-B1-EhHChcVk5Ev1rKRQ',
    appId: '1:138938830840:ios:a819f752f35311e8b8900d',
    messagingSenderId: '138938830840',
    projectId: 'todo-db9a3',
    storageBucket: 'todo-db9a3.appspot.com',
    iosBundleId: 'com.example.todoApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDntiT_eQb285W-B1-EhHChcVk5Ev1rKRQ',
    appId: '1:138938830840:ios:a819f752f35311e8b8900d',
    messagingSenderId: '138938830840',
    projectId: 'todo-db9a3',
    storageBucket: 'todo-db9a3.appspot.com',
    iosBundleId: 'com.example.todoApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIDLhU3h8khQFQ0dtJXoR48dcKNK6y6SI',
    appId: '1:138938830840:web:bc7e259110b979acb8900d',
    messagingSenderId: '138938830840',
    projectId: 'todo-db9a3',
    authDomain: 'todo-db9a3.firebaseapp.com',
    storageBucket: 'todo-db9a3.appspot.com',
  );
}
